// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hiwjjaiakizxgophchdt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhpd2pqYWlha2l6eGdvcGhjaGR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMTM0NTMsImV4cCI6MjA2Mzg4OTQ1M30.UOwTSnU4EKJHHP3ylNJ1-pdyreax7oM4AVYvOFErYtI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);